% Intensity Measures Panels and Buttons

IM.Panel{1}=uipanel('Parent',MainAxes.Tabs{5},'Units','normalized',...
    'Position',[0.00 0.20 0.5 0.8],'Title','Reference Accelerogram IMs','BorderType','none');

IM.Panel{2}=uipanel('Parent',MainAxes.Tabs{5},'Units','normalized',...
    'Position',[0.50 0.20 0.5 0.8],'Title','Synthetic Accelerogram IMs','BorderType','none');

IM.Panel{3}=uipanel('Parent',MainAxes.Tabs{5},'Units','normalized',...
    'Position',[0.00 0.00 0.5 0.2],'Title','Matching parameters','BorderType','none');

%% Buttons for Reference Accelerogram IMs
IM.Names={'PGA =','PGV =','PGD =','CAV =','Ia =','Ic =','Arms =','ASI =','HI =','t5 =','DS =','t95 ='};
IM.Units={'[ g ]','[ m/s ]','[ m ]','[ cm/s ]','[ m/s ]','[ - ]','[ g ]','[ - ]','[ m ]','[ s ]','[ s ]','[ s ]'};
% IM.Tooltips={'Peak Ground Acceleration','Peak Ground Velocity','Peak Ground Displacement',...
%             'Cumulative Absolute Velocity','Arias Intensity','Arias Intensity','Root-Mean Square of Acceleration',...
%             'Acceleration Spectral Intensity','Housner Intensity','Time at 5% Arias Intensity','Significant Duration','Time at 95% Arias Intensity'};

for i=1:36
    if i<13
        %labels
IM.Buttons{1}.Edit{i}=uicontrol('Parent',IM.Panel{1},'Style','edit',...
    'Units','normalized','Position',[0.05 1-0.08*i 0.20 0.055],...
    'string',IM.Names{i},'Enable','inactive','BackgroundColor',[0.941 0.941 0.941],'HorizontalAlignment','right');
    elseif i>12 && i<25
        %values
IM.Buttons{1}.Edit{i}=uicontrol('Parent',IM.Panel{1},'Style','edit',...
    'Units','normalized','Position',[0.25 1-0.08*(i-12) 0.25 0.055],...
    'Enable','inactive','HorizontalAlignment','right');
    else
        %units
IM.Buttons{1}.Edit{i}=uicontrol('Parent',IM.Panel{1},'Style','edit',...
    'Units','normalized','Position',[0.50 1-0.08*(i-24) 0.20 0.055],...
    'string',IM.Units{i-24},'Enable','inactive','BackgroundColor',[0.941 0.941 0.941],'HorizontalAlignment','center');
    end
end

%% Buttons for Synthetic Accelerogram IMs

for i=1:36
    if i<13
        %labels
IM.Buttons{2}.Edit{i}=uicontrol('Parent',IM.Panel{2},'Style','edit',...
    'Units','normalized','Position',[0.05 1-0.08*i 0.20 0.055],...
    'string',IM.Names{i},'Enable','inactive','BackgroundColor',[0.941 0.941 0.941],'HorizontalAlignment','right');
    elseif i>12 && i<25
        %values
IM.Buttons{2}.Edit{i}=uicontrol('Parent',IM.Panel{2},'Style','edit',...
    'Units','normalized','Position',[0.25 1-0.08*(i-12) 0.25 0.055],...
    'Enable','inactive','HorizontalAlignment','right');
    else
        %units
IM.Buttons{2}.Edit{i}=uicontrol('Parent',IM.Panel{2},'Style','edit',...
    'Units','normalized','Position',[0.50 1-0.08*(i-24) 0.20 0.055],...
    'string',IM.Units{i-24},'Enable','inactive','BackgroundColor',[0.941 0.941 0.941],'HorizontalAlignment','center');
    end
end

%% Buttons for matching parameters


%Labels
IM.Buttons{3}.Edit{1}=uicontrol('Parent',IM.Panel{3},'Style','edit',...
    'Units','normalized','Position',[0.05 0.65 0.25 0.25],...
    'string','Num.Iter. =','Enable','inactive','BackgroundColor',[0.941 0.941 0.941],'HorizontalAlignment','right');
IM.Buttons{3}.Edit{2}=uicontrol('Parent',IM.Panel{3},'Style','edit',...
    'Units','normalized','Position',[0.05 0.30 0.25 0.25],...
    'string','Max.Err. =','Enable','inactive','BackgroundColor',[0.941 0.941 0.941],'HorizontalAlignment','right');
%Values
IM.Buttons{3}.Edit{3}=uicontrol('Parent',IM.Panel{3},'Style','edit',...
    'Units','normalized','Position',[0.30 0.65 0.25 0.25],...
    'Enable','inactive','HorizontalAlignment','right');
IM.Buttons{3}.Edit{4}=uicontrol('Parent',IM.Panel{3},'Style','edit',...
    'Units','normalized','Position',[0.30 0.30 0.25 0.25],...
    'Enable','inactive','HorizontalAlignment','right');
%Units
IM.Buttons{3}.Edit{5}=uicontrol('Parent',IM.Panel{3},'Style','edit',...
    'Units','normalized','Position',[0.55 0.65 0.15 0.25],...
    'string','[ - ]','Enable','inactive','BackgroundColor',[0.941 0.941 0.941],'HorizontalAlignment','center');
IM.Buttons{3}.Edit{6}=uicontrol('Parent',IM.Panel{3},'Style','edit',...
    'Units','normalized','Position',[0.55 0.30 0.15 0.25],...
    'string','[ % ]','Enable','inactive','BackgroundColor',[0.941 0.941 0.941],'HorizontalAlignment','center');
