% Intensity Measures Panels and Buttons

IM.Panel{1}=uipanel('Parent',MainAxes.Tabs{5},'Units','normalized',...
    'Position',[0.00 0.40 0.5 0.6],'Title','Reference Accelerogram IMs','BorderType','none');

IM.Panel{2}=uipanel('Parent',MainAxes.Tabs{5},'Units','normalized',...
    'Position',[0.50 0.40 0.5 0.6],'Title','Synthetic Accelerogram IMs','BorderType','none');

IM.Panel{3}=uipanel('Parent',MainAxes.Tabs{5},'Units','normalized',...
    'Position',[0.00 0.00 0.5 0.4],'Title','Matching parameters','BorderType','none');

%% Buttons for Reference Accelerogram IMs

%Labels
IM.Buttons{1}.Edit{1}=uicontrol('Parent',IM.Panel{1},'Style','edit',...
    'Units','normalized','Position',[0.05 0.90 0.20 0.07],...
    'string','PGA =','Enable','inactive','BackgroundColor',[0.941 0.941 0.941],'HorizontalAlignment','right');
IM.Buttons{1}.Edit{2}=uicontrol('Parent',IM.Panel{1},'Style','edit',...
    'Units','normalized','Position',[0.05 0.80 0.20 0.07],...
    'string','CAV =','Enable','inactive','BackgroundColor',[0.941 0.941 0.941],'HorizontalAlignment','right');
IM.Buttons{1}.Edit{3}=uicontrol('Parent',IM.Panel{1},'Style','edit',...
    'Units','normalized','Position',[0.05 0.70 0.20 0.07],...
    'string','Ia =','Enable','inactive','BackgroundColor',[0.941 0.941 0.941],'HorizontalAlignment','right');
IM.Buttons{1}.Edit{4}=uicontrol('Parent',IM.Panel{1},'Style','edit',...
    'Units','normalized','Position',[0.05 0.60 0.20 0.07],...
    'string','Ic =','Enable','inactive','BackgroundColor',[0.941 0.941 0.941],'HorizontalAlignment','right');
IM.Buttons{1}.Edit{5}=uicontrol('Parent',IM.Panel{1},'Style','edit',...
    'Units','normalized','Position',[0.05 0.50 0.20 0.07],...
    'string','Arms =','Enable','inactive','BackgroundColor',[0.941 0.941 0.941],'HorizontalAlignment','right');
IM.Buttons{1}.Edit{6}=uicontrol('Parent',IM.Panel{1},'Style','edit',...
    'Units','normalized','Position',[0.05 0.40 0.20 0.07],...
    'string','ASI =','Enable','inactive','BackgroundColor',[0.941 0.941 0.941],'HorizontalAlignment','right');
IM.Buttons{1}.Edit{7}=uicontrol('Parent',IM.Panel{1},'Style','edit',...
    'Units','normalized','Position',[0.05 0.30 0.20 0.07],...
    'string','t5 =','Enable','inactive','BackgroundColor',[0.941 0.941 0.941],'HorizontalAlignment','right');
IM.Buttons{1}.Edit{8}=uicontrol('Parent',IM.Panel{1},'Style','edit',...
    'Units','normalized','Position',[0.05 0.20 0.20 0.07],...
    'string','DS =','Enable','inactive','BackgroundColor',[0.941 0.941 0.941],'HorizontalAlignment','right');
IM.Buttons{1}.Edit{9}=uicontrol('Parent',IM.Panel{1},'Style','edit',...
    'Units','normalized','Position',[0.05 0.10 0.20 0.07],...
    'string','t95 =','Enable','inactive','BackgroundColor',[0.941 0.941 0.941],'HorizontalAlignment','right');

%Values
IM.Buttons{1}.Edit{10}=uicontrol('Parent',IM.Panel{1},'Style','edit',...
    'Units','normalized','Position',[0.25 0.90 0.25 0.07],...
    'Enable','inactive','HorizontalAlignment','right');
IM.Buttons{1}.Edit{11}=uicontrol('Parent',IM.Panel{1},'Style','edit',...
    'Units','normalized','Position',[0.25 0.80 0.25 0.07],...
    'Enable','inactive','HorizontalAlignment','right');
IM.Buttons{1}.Edit{12}=uicontrol('Parent',IM.Panel{1},'Style','edit',...
    'Units','normalized','Position',[0.25 0.70 0.25 0.07],...
    'Enable','inactive','HorizontalAlignment','right');
IM.Buttons{1}.Edit{13}=uicontrol('Parent',IM.Panel{1},'Style','edit',...
    'Units','normalized','Position',[0.25 0.60 0.25 0.07],...
    'Enable','inactive','HorizontalAlignment','right');
IM.Buttons{1}.Edit{14}=uicontrol('Parent',IM.Panel{1},'Style','edit',...
    'Units','normalized','Position',[0.25 0.50 0.25 0.07],...
    'Enable','inactive','HorizontalAlignment','right');
IM.Buttons{1}.Edit{15}=uicontrol('Parent',IM.Panel{1},'Style','edit',...
    'Units','normalized','Position',[0.25 0.40 0.25 0.07],...
    'Enable','inactive','HorizontalAlignment','right');
IM.Buttons{1}.Edit{16}=uicontrol('Parent',IM.Panel{1},'Style','edit',...
    'Units','normalized','Position',[0.25 0.30 0.25 0.07],...
    'Enable','inactive','HorizontalAlignment','right');
IM.Buttons{1}.Edit{17}=uicontrol('Parent',IM.Panel{1},'Style','edit',...
    'Units','normalized','Position',[0.25 0.20 0.25 0.07],...
    'Enable','inactive','HorizontalAlignment','right');
IM.Buttons{1}.Edit{18}=uicontrol('Parent',IM.Panel{1},'Style','edit',...
    'Units','normalized','Position',[0.25 0.10 0.25 0.07],...
    'Enable','inactive','HorizontalAlignment','right');

%Units
IM.Buttons{1}.Edit{19}=uicontrol('Parent',IM.Panel{1},'Style','edit',...
    'Units','normalized','Position',[0.50 0.90 0.15 0.07],...
    'string','[ g ]','Enable','inactive','BackgroundColor',[0.941 0.941 0.941],'HorizontalAlignment','center');
IM.Buttons{1}.Edit{20}=uicontrol('Parent',IM.Panel{1},'Style','edit',...
    'Units','normalized','Position',[0.50 0.80 0.15 0.07],...
    'string','[cm/s]','Enable','inactive','BackgroundColor',[0.941 0.941 0.941],'HorizontalAlignment','center');
IM.Buttons{1}.Edit{21}=uicontrol('Parent',IM.Panel{1},'Style','edit',...
    'Units','normalized','Position',[0.50 0.70 0.15 0.07],...
    'string','[m/s]','Enable','inactive','BackgroundColor',[0.941 0.941 0.941],'HorizontalAlignment','center');
IM.Buttons{1}.Edit{22}=uicontrol('Parent',IM.Panel{1},'Style','edit',...
    'Units','normalized','Position',[0.50 0.60 0.15 0.07],...
    'string','[ - ]','Enable','inactive','BackgroundColor',[0.941 0.941 0.941],'HorizontalAlignment','center');
IM.Buttons{1}.Edit{23}=uicontrol('Parent',IM.Panel{1},'Style','edit',...
    'Units','normalized','Position',[0.50 0.50 0.15 0.07],...
    'string','[ g ]','Enable','inactive','BackgroundColor',[0.941 0.941 0.941],'HorizontalAlignment','center');
IM.Buttons{1}.Edit{24}=uicontrol('Parent',IM.Panel{1},'Style','edit',...
    'Units','normalized','Position',[0.50 0.40 0.15 0.07],...
    'string','[ - ]','Enable','inactive','BackgroundColor',[0.941 0.941 0.941],'HorizontalAlignment','center');
IM.Buttons{1}.Edit{25}=uicontrol('Parent',IM.Panel{1},'Style','edit',...
    'Units','normalized','Position',[0.50 0.30 0.15 0.07],...
    'string','[ s ]','Enable','inactive','BackgroundColor',[0.941 0.941 0.941],'HorizontalAlignment','center');
IM.Buttons{1}.Edit{26}=uicontrol('Parent',IM.Panel{1},'Style','edit',...
    'Units','normalized','Position',[0.50 0.20 0.15 0.07],...
    'string','[ s ]','Enable','inactive','BackgroundColor',[0.941 0.941 0.941],'HorizontalAlignment','center');
IM.Buttons{1}.Edit{27}=uicontrol('Parent',IM.Panel{1},'Style','edit',...
    'Units','normalized','Position',[0.50 0.10 0.15 0.07],...
    'string','[ s ]','Enable','inactive','BackgroundColor',[0.941 0.941 0.941],'HorizontalAlignment','center');

%% Buttons for Synthetic Accelerogram IMs

%Labels
IM.Buttons{2}.Edit{1}=uicontrol('Parent',IM.Panel{2},'Style','edit',...
    'Units','normalized','Position',[0.05 0.90 0.20 0.07],...
    'string','PGA =','Enable','inactive','BackgroundColor',[0.941 0.941 0.941],'HorizontalAlignment','right');
IM.Buttons{2}.Edit{2}=uicontrol('Parent',IM.Panel{2},'Style','edit',...
    'Units','normalized','Position',[0.05 0.80 0.20 0.07],...
    'string','CAV =','Enable','inactive','BackgroundColor',[0.941 0.941 0.941],'HorizontalAlignment','right');
IM.Buttons{2}.Edit{3}=uicontrol('Parent',IM.Panel{2},'Style','edit',...
    'Units','normalized','Position',[0.05 0.70 0.20 0.07],...
    'string','Ia =','Enable','inactive','BackgroundColor',[0.941 0.941 0.941],'HorizontalAlignment','right');
IM.Buttons{2}.Edit{4}=uicontrol('Parent',IM.Panel{2},'Style','edit',...
    'Units','normalized','Position',[0.05 0.60 0.20 0.07],...
    'string','Ic =','Enable','inactive','BackgroundColor',[0.941 0.941 0.941],'HorizontalAlignment','right');
IM.Buttons{2}.Edit{5}=uicontrol('Parent',IM.Panel{2},'Style','edit',...
    'Units','normalized','Position',[0.05 0.50 0.20 0.07],...
    'string','Arms =','Enable','inactive','BackgroundColor',[0.941 0.941 0.941],'HorizontalAlignment','right');
IM.Buttons{2}.Edit{6}=uicontrol('Parent',IM.Panel{2},'Style','edit',...
    'Units','normalized','Position',[0.05 0.40 0.20 0.07],...
    'string','ASI =','Enable','inactive','BackgroundColor',[0.941 0.941 0.941],'HorizontalAlignment','right');
IM.Buttons{2}.Edit{7}=uicontrol('Parent',IM.Panel{2},'Style','edit',...
    'Units','normalized','Position',[0.05 0.30 0.20 0.07],...
    'string','t5 =','Enable','inactive','BackgroundColor',[0.941 0.941 0.941],'HorizontalAlignment','right');
IM.Buttons{2}.Edit{8}=uicontrol('Parent',IM.Panel{2},'Style','edit',...
    'Units','normalized','Position',[0.05 0.20 0.20 0.07],...
    'string','DS =','Enable','inactive','BackgroundColor',[0.941 0.941 0.941],'HorizontalAlignment','right');
IM.Buttons{2}.Edit{9}=uicontrol('Parent',IM.Panel{2},'Style','edit',...
    'Units','normalized','Position',[0.05 0.10 0.20 0.07],...
    'string','t95 =','Enable','inactive','BackgroundColor',[0.941 0.941 0.941],'HorizontalAlignment','right');

%Values
IM.Buttons{2}.Edit{10}=uicontrol('Parent',IM.Panel{2},'Style','edit',...
    'Units','normalized','Position',[0.25 0.90 0.25 0.07],...
    'Enable','inactive','HorizontalAlignment','right');
IM.Buttons{2}.Edit{11}=uicontrol('Parent',IM.Panel{2},'Style','edit',...
    'Units','normalized','Position',[0.25 0.80 0.25 0.07],...
    'Enable','inactive','HorizontalAlignment','right');
IM.Buttons{2}.Edit{12}=uicontrol('Parent',IM.Panel{2},'Style','edit',...
    'Units','normalized','Position',[0.25 0.70 0.25 0.07],...
    'Enable','inactive','HorizontalAlignment','right');
IM.Buttons{2}.Edit{13}=uicontrol('Parent',IM.Panel{2},'Style','edit',...
    'Units','normalized','Position',[0.25 0.60 0.25 0.07],...
    'Enable','inactive','HorizontalAlignment','right');
IM.Buttons{2}.Edit{14}=uicontrol('Parent',IM.Panel{2},'Style','edit',...
    'Units','normalized','Position',[0.25 0.50 0.25 0.07],...
    'Enable','inactive','HorizontalAlignment','right');
IM.Buttons{2}.Edit{15}=uicontrol('Parent',IM.Panel{2},'Style','edit',...
    'Units','normalized','Position',[0.25 0.40 0.25 0.07],...
    'Enable','inactive','HorizontalAlignment','right');
IM.Buttons{2}.Edit{16}=uicontrol('Parent',IM.Panel{2},'Style','edit',...
    'Units','normalized','Position',[0.25 0.30 0.25 0.07],...
    'Enable','inactive','HorizontalAlignment','right');
IM.Buttons{2}.Edit{17}=uicontrol('Parent',IM.Panel{2},'Style','edit',...
    'Units','normalized','Position',[0.25 0.20 0.25 0.07],...
    'Enable','inactive','HorizontalAlignment','right');
IM.Buttons{2}.Edit{18}=uicontrol('Parent',IM.Panel{2},'Style','edit',...
    'Units','normalized','Position',[0.25 0.10 0.25 0.07],...
    'Enable','inactive','HorizontalAlignment','right');

%Units
IM.Buttons{2}.Edit{19}=uicontrol('Parent',IM.Panel{2},'Style','edit',...
    'Units','normalized','Position',[0.50 0.90 0.15 0.07],...
    'string','[ g ]','Enable','inactive','BackgroundColor',[0.941 0.941 0.941],'HorizontalAlignment','center');
IM.Buttons{2}.Edit{20}=uicontrol('Parent',IM.Panel{2},'Style','edit',...
    'Units','normalized','Position',[0.50 0.80 0.15 0.07],...
    'string','[cm/s]','Enable','inactive','BackgroundColor',[0.941 0.941 0.941],'HorizontalAlignment','center');
IM.Buttons{2}.Edit{21}=uicontrol('Parent',IM.Panel{2},'Style','edit',...
    'Units','normalized','Position',[0.50 0.70 0.15 0.07],...
    'string','[m/s]','Enable','inactive','BackgroundColor',[0.941 0.941 0.941],'HorizontalAlignment','center');
IM.Buttons{2}.Edit{22}=uicontrol('Parent',IM.Panel{2},'Style','edit',...
    'Units','normalized','Position',[0.50 0.60 0.15 0.07],...
    'string','[ - ]','Enable','inactive','BackgroundColor',[0.941 0.941 0.941],'HorizontalAlignment','center');
IM.Buttons{2}.Edit{23}=uicontrol('Parent',IM.Panel{2},'Style','edit',...
    'Units','normalized','Position',[0.50 0.50 0.15 0.07],...
    'string','[ g ]','Enable','inactive','BackgroundColor',[0.941 0.941 0.941],'HorizontalAlignment','center');
IM.Buttons{2}.Edit{24}=uicontrol('Parent',IM.Panel{2},'Style','edit',...
    'Units','normalized','Position',[0.50 0.40 0.15 0.07],...
    'string','[ - ]','Enable','inactive','BackgroundColor',[0.941 0.941 0.941],'HorizontalAlignment','center');
IM.Buttons{2}.Edit{25}=uicontrol('Parent',IM.Panel{2},'Style','edit',...
    'Units','normalized','Position',[0.50 0.30 0.15 0.07],...
    'string','[ s ]','Enable','inactive','BackgroundColor',[0.941 0.941 0.941],'HorizontalAlignment','center');
IM.Buttons{2}.Edit{26}=uicontrol('Parent',IM.Panel{2},'Style','edit',...
    'Units','normalized','Position',[0.50 0.20 0.15 0.07],...
    'string','[ s ]','Enable','inactive','BackgroundColor',[0.941 0.941 0.941],'HorizontalAlignment','center');
IM.Buttons{2}.Edit{27}=uicontrol('Parent',IM.Panel{2},'Style','edit',...
    'Units','normalized','Position',[0.50 0.10 0.15 0.07],...
    'string','[ s ]','Enable','inactive','BackgroundColor',[0.941 0.941 0.941],'HorizontalAlignment','center');

%% Buttons for matching parameters

%Labels
IM.Buttons{3}.Edit{1}=uicontrol('Parent',IM.Panel{3},'Style','edit',...
    'Units','normalized','Position',[0.05 0.85 0.25 0.10],...
    'string','Num.Iter. =','Enable','inactive','BackgroundColor',[0.941 0.941 0.941],'HorizontalAlignment','right');
IM.Buttons{3}.Edit{2}=uicontrol('Parent',IM.Panel{3},'Style','edit',...
    'Units','normalized','Position',[0.05 0.70 0.25 0.10],...
    'string','Max.Err. =','Enable','inactive','BackgroundColor',[0.941 0.941 0.941],'HorizontalAlignment','right');
%Values
IM.Buttons{3}.Edit{3}=uicontrol('Parent',IM.Panel{3},'Style','edit',...
    'Units','normalized','Position',[0.30 0.85 0.25 0.10],...
    'Enable','inactive','HorizontalAlignment','right');
IM.Buttons{3}.Edit{4}=uicontrol('Parent',IM.Panel{3},'Style','edit',...
    'Units','normalized','Position',[0.30 0.70 0.25 0.10],...
    'Enable','inactive','HorizontalAlignment','right');
%Units
IM.Buttons{3}.Edit{5}=uicontrol('Parent',IM.Panel{3},'Style','edit',...
    'Units','normalized','Position',[0.55 0.85 0.15 0.10],...
    'string','[ - ]','Enable','inactive','BackgroundColor',[0.941 0.941 0.941],'HorizontalAlignment','center');
IM.Buttons{3}.Edit{6}=uicontrol('Parent',IM.Panel{3},'Style','edit',...
    'Units','normalized','Position',[0.55 0.70 0.15 0.10],...
    'string','[ % ]','Enable','inactive','BackgroundColor',[0.941 0.941 0.941],'HorizontalAlignment','center');
