% Method Panel 2: Gaussian Noise

% === Intensity Function and Base Signal Generation ===
MethodButtons{2}.Panel{2} = uipanel('Parent',MethodPanel{2},'Units','normalized',...
    'Position',[0 0.60 1.0 0.40],'Title','Base Signal Generator','BorderType','none');
MethodButtons{2}.Text{5} = uicontrol('Parent',MethodButtons{2}.Panel{2},'Style','text',...
    'Units','normalized','Position',[0.05 0.75 0.9 0.20],...
    'String','Select the intensity function to shape the signal.','HorizontalAlignment','left');
MethodButtons{2}.Button{5} = uicontrol('Parent',MethodButtons{2}.Panel{2},'Style','pushbutton',...
    'Units','normalized','Position',[0.05 0.55 0.9 0.20],...
    'String','Select Intensity Function','HorizontalAlignment','center');
MethodButtons{2}.Text{6} = uicontrol('Parent',MethodButtons{2}.Panel{2},'Style','text',...
    'Units','normalized','Position',[0.05 0.25 0.9 0.20],...
    'String','Generate the base synthetic signal to be used in the adjustment process.','HorizontalAlignment','left');
MethodButtons{2}.Button{6} = uicontrol('Parent',MethodButtons{2}.Panel{2},'Style','pushbutton',...
    'Units','normalized','Position',[0.05 0.05 0.9 0.20],...
    'String','Generate Base Signal','HorizontalAlignment','center');

% === Target Spectrum Panel ===
MethodButtons{2}.Panel{3} = uipanel('Parent',MethodPanel{2},'Units','normalized',...
    'Position',[0 0.40 1.0 0.20],'Title','Target Spectrum','BorderType','none');
MethodButtons{2}.Text{3} = uicontrol('Parent',MethodButtons{2}.Panel{3},'Style','text',...
    'Units','normalized','Position',[0.05 0.65 0.9 0.3],...
    'String','Specify the design or response spectrum to be used as target.','HorizontalAlignment','left');
MethodButtons{2}.Button{3} = uicontrol('Parent',MethodButtons{2}.Panel{3},'Style','pushbutton',...
    'Units','normalized','Position',[0.05 0.15 0.9 0.4],...
    'String','Select Spectrum','HorizontalAlignment','center');

% === Analysis Parameters Panel ===
MethodButtons{2}.Panel{4} = uipanel('Parent',MethodPanel{2},'Units','normalized',...
    'Position',[0 0.10 1.0 0.30],'Title','Analysis Settings','BorderType','none');
MethodButtons{2}.Text{4} = uicontrol('Parent',MethodButtons{2}.Panel{4},'Style','text',...
    'Units','normalized','Position',[0.05 0.65 0.9 0.3],...
    'String','Set the maximum number of iterations and the tolerance (error in %) for analysis.','HorizontalAlignment','left');
MethodButtons{2}.Edit{7} = uicontrol('Parent',MethodButtons{2}.Panel{4},'Style','Edit',...
    'Units','normalized','Position',[0.05 0.4 0.25 0.20],...
    'String','Max.Iter.','HorizontalAlignment','center','Enable','inactive','BackgroundColor',[0.941 0.941 0.941]);
MethodButtons{2}.Edit{8} = uicontrol('Parent',MethodButtons{2}.Panel{4},'Style','Edit',...
    'Units','normalized','Position',[0.30 0.4 0.15 0.20],'String','10',...
    'HorizontalAlignment','center','Enable','on');
MethodButtons{2}.Edit{9} = uicontrol('Parent',MethodButtons{2}.Panel{4},'Style','Edit',...
    'Units','normalized','Position',[0.55 0.4 0.25 0.20],...
    'String','Max.Err.[%]','HorizontalAlignment','center','Enable','inactive','BackgroundColor',[0.941 0.941 0.941]);
MethodButtons{2}.Edit{10} = uicontrol('Parent',MethodButtons{2}.Panel{4},'Style','Edit',...
    'Units','normalized','Position',[0.80 0.4 0.15 0.20],...
    'Enable','on','HorizontalAlignment','center','String','10');
MethodButtons{2}.Button{4} = uicontrol('Parent',MethodButtons{2}.Panel{4},'Style','pushbutton',...
    'Units','normalized','Position',[0.05 0.1 0.9 0.25],...
    'String','Run Analysis','HorizontalAlignment','center');