% Method Panel 1: Reference Accelerogram

% === Reference Earthquake Panel ===
MethodButtons{1}.Panel{1} = uipanel('Parent',MethodPanel{1},'Units','normalized',...
    'Position',[0 0.70 1.0 0.30],'Title','Reference Accelerogram','BorderType','none');

MethodButtons{1}.Text{1} = uicontrol('Parent',MethodButtons{1}.Panel{1},'Style','text',...
    'Units','normalized','Position',[0.05 0.80 0.9 0.15],...
    'String','Select a reference accelerogram record.','HorizontalAlignment','left');

MethodButtons{1}.Edit{1} = uicontrol('Parent',MethodButtons{1}.Panel{1},'Style','Edit',...
    'Units','normalized','Position',[0.05 0.60 0.20 0.20],...
    'String','File:','HorizontalAlignment','center','Enable','inactive','BackgroundColor',[0.941 0.941 0.941]);
MethodButtons{1}.Edit{2} = uicontrol('Parent',MethodButtons{1}.Panel{1},'Style','Edit',...
    'Units','normalized','Position',[0.25 0.60 0.40 0.20],...
    'Enable','inactive','HorizontalAlignment','left');
MethodButtons{1}.Button{1} = uicontrol('Parent',MethodButtons{1}.Panel{1},'Style','pushbutton',...
    'Units','normalized','Position',[0.70 0.60 0.25 0.20],...
    'String','Browse','HorizontalAlignment','center');

MethodButtons{1}.Text{2} = uicontrol('Parent',MethodButtons{1}.Panel{1},'Style','text',...
    'Units','normalized','Position',[0.05 0.35 0.9 0.2],...
    'String','Specify the resampling frequency (Fr) for the reference accelerogram. Then press Load.','HorizontalAlignment','left');

MethodButtons{1}.Edit{3} = uicontrol('Parent',MethodButtons{1}.Panel{1},'Style','Edit',...
    'Units','normalized','Position',[0.05 0.10 0.15 0.20],...
    'String','Fs =','HorizontalAlignment','center','Enable','inactive','BackgroundColor',[0.941 0.941 0.941]);
MethodButtons{1}.Edit{4} = uicontrol('Parent',MethodButtons{1}.Panel{1},'Style','Edit',...
    'Units','normalized','Position',[0.20 0.10 0.125 0.20],...
    'HorizontalAlignment','center','Enable','inactive','BackgroundColor',[0.9 0.9 0.9]);
MethodButtons{1}.Edit{5} = uicontrol('Parent',MethodButtons{1}.Panel{1},'Style','Edit',...
    'Units','normalized','Position',[0.375 0.10 0.15 0.20],...
    'String','Fr =','HorizontalAlignment','center','Enable','inactive','BackgroundColor',[0.941 0.941 0.941]);
MethodButtons{1}.Edit{6} = uicontrol('Parent',MethodButtons{1}.Panel{1},'Style','Edit',...
    'Units','normalized','Position',[0.525 0.10 0.125 0.20],...
    'Enable','inactive','HorizontalAlignment','center');
MethodButtons{1}.Button{2} = uicontrol('Parent',MethodButtons{1}.Panel{1},'Style','pushbutton',...
    'Units','normalized','Position',[0.70 0.10 0.25 0.20],...
    'String','Load','HorizontalAlignment','center');

% === Target Spectrum Panel ===
MethodButtons{1}.Panel{2} = uipanel('Parent',MethodPanel{1},'Units','normalized',...
    'Position',[0 0.50 1.0 0.20],'Title','Target Spectrum','BorderType','none');
MethodButtons{1}.Text{3} = uicontrol('Parent',MethodButtons{1}.Panel{2},'Style','text',...
    'Units','normalized','Position',[0.05 0.65 0.9 0.3],...
    'String','Specify the design or response spectrum to be used as target.','HorizontalAlignment','left');

MethodButtons{1}.Button{3} = uicontrol('Parent',MethodButtons{1}.Panel{2},'Style','pushbutton',...
    'Units','normalized','Position',[0.05 0.15 0.9 0.4],...
    'String','Select Spectrum','HorizontalAlignment','center');

% === Analysis Parameters Panel ===
MethodButtons{1}.Panel{3} = uipanel('Parent',MethodPanel{1},'Units','normalized',...
    'Position',[0 0.20 1.0 0.30],'Title','Analysis Settings','BorderType','none');

MethodButtons{1}.Text{4} = uicontrol('Parent',MethodButtons{1}.Panel{3},'Style','text',...
    'Units','normalized','Position',[0.05 0.65 0.9 0.3],...
    'String','Set the maximum number of iterations and the tolerance (error in %) for analysis.','HorizontalAlignment','left');

MethodButtons{1}.Edit{7} = uicontrol('Parent',MethodButtons{1}.Panel{3},'Style','Edit',...
    'Units','normalized','Position',[0.05 0.4 0.25 0.20],...
    'String','Max.Iter.','HorizontalAlignment','center','Enable','inactive','BackgroundColor',[0.941 0.941 0.941]);
MethodButtons{1}.Edit{8} = uicontrol('Parent',MethodButtons{1}.Panel{3},'Style','Edit',...
    'Units','normalized','Position',[0.30 0.4 0.15 0.20],'String','10',...
    'HorizontalAlignment','center','Enable','on');
MethodButtons{1}.Edit{9} = uicontrol('Parent',MethodButtons{1}.Panel{3},'Style','Edit',...
    'Units','normalized','Position',[0.55 0.4 0.25 0.20],...
    'String','Max.Err.[%]','HorizontalAlignment','center','Enable','inactive','BackgroundColor',[0.941 0.941 0.941]);
MethodButtons{1}.Edit{10} = uicontrol('Parent',MethodButtons{1}.Panel{3},'Style','Edit',...
    'Units','normalized','Position',[0.80 0.4 0.15 0.20],...
    'Enable','on','HorizontalAlignment','center','String','10');

MethodButtons{1}.Button{4} = uicontrol('Parent',MethodButtons{1}.Panel{3},'Style','pushbutton',...
    'Units','normalized','Position',[0.05 0.1 0.9 0.25],...
    'String','Run Analysis','HorizontalAlignment','center');